apiVersion: v1
kind: Namespace
metadata:
  name: portal
---
apiVersion: v1
kind: Service
metadata:
  name: sms-ui
  namespace: portal
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: ui-port
      protocol: TCP
      port: 80
      targetPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-ui
  namespace: portal
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: sms-ui
          image: sms-ui:1.0
          resources:
            requests:
              memory: 30Mi
              cpu: 50m
            limits:
              memory: 50Mi
              cpu: 100m
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: ui-port
